networks:
  default:
    driver: bridge # Using bridge network in docker 
    name: roboshop # Default name roboshop
    external: false # True if we create network manually

#######################################################################################################################

services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: kirankumarkosuri/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db

#######################################################################################################################

  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: kirankumarkosuri/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb

#######################################################################################################################
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kirankumarkosuri/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment

#######################################################################################################################

  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data

#######################################################################################################################

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: kirankumarkosuri/user:v1
    container_name:  user
    depends_on:
    - redis
    - mongodb

#######################################################################################################################
  
  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    image: kirankumarkosuri/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue

#######################################################################################################################

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: kirankumarkosuri/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

#######################################################################################################################

  shipping:
    build:
      context: ./shipping
      dockerfile: Dockerfile
    image: kirankumarkosuri/shipping:v1
    container_name: shipping
    depends_on:
    - cart
    - mysql

#######################################################################################################################

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
      - rabbitmq:/var/lib/rabbitmq

#######################################################################################################################

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    image: kirankumarkosuri/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
    - user
    - cart

#######################################################################################################################

volumes: 
    mongodb: #  This is equal to "docker volume create mongodb"
    redis:
    mysql:
    rabbitmq:

  

