networks:
  default:
    driver: bridge
    name: roboshop
    external: false # true if you have created network manually using docker network command

#########################################################################################################################################

services:
  mongodb:
    build: ./mongodb
    image: kirankumarkosuri/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db

#########################################################################################################################################
  
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: kirankumarkosuri/catalogue:v1
    container_name: catalogue
    depends_on: 
    - mongodb

#########################################################################################################################################

  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
    
#########################################################################################################################################
  
  mysql:
    build: ./mysql
    image: kirankumarkosuri/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql

#########################################################################################################################################

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123

#########################################################################################################################################

  user:
    build: ./user
    image: kirankumarkosuri/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis

#########################################################################################################################################

  cart:
    build: ./cart
    image: kirankumarkosuri/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis

#########################################################################################################################################

  shipping:
    build: ./shipping
    image: kirankumarkosuri/shipping:v1
    container_name: shipping
    depends_on:
    - cart
    - mysql

#########################################################################################################################################
  
  payment:
    build: ./payment
    image: kirankumarkosuri/payment:v1
    container_name: payment
    depends_on:
    - cart
    - user
    - rabbitmq

#########################################################################################################################################

  frontend:
    build: ./frontend
    image: kirankumarkosuri/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment

#########################################################################################################################################

volumes:

    mongodb: # This equal to --> docker volume create mongodb
    redis: # This equal to --> docker volume create redis
    mysql: # This equal to --> docker volume create mysql
    rabbitmq: # This equal to --> docker volume create rabbitmq

#########################################################################################################################################